### ISSUE TITLE
Support for getting statistics on a commander profile

### ISSUE THREAD

**Issue by johnobrien** [inorton/EDMCHits#10]
I'd like the ability to message !stats to another commander and then EDMCHits would respond with the number of players that the commander to whom the message was sent has been logged as killing in HITS.

I'm happy to contribute the changes to the load.py file, but it looks like it would require a new response be supported by the edmc.edhits.space:8080 in order to enable something like this to work.

Would you be open to this idea?

**Comment by inorton** [comment]
Hi @johnobrien that's a great idea, infact I'm working on that very idea myself.  I should be automatic rather than requiring someone to type.  I know of someone else also working with this goal in mind 👍

**Comment by johnobrien** [comment]
Well I'm happy to help. Do we need Frontier to make enhancements to make it
a reality or do you have an approach in mind that doesn't require that?

**Comment by inorton** [comment]
@johnobrien My own server end for this is https://github.com/inorton/EDTrust. I've not been running it recently as my server doesn't have quite enough RAM to do that and HITS at the same time (512mb VPS)

I have the server working enough for one or more people to manage a "list" which can contain "good/bad" cmdrs, I've not done much to the client side yet

**Comment by inorton** [comment]
Hi @johnobrien you might want to check out https://github.com/seldonlabs/OmniScanner
