### ISSUE TITLE
Python 3.x support 

### ISSUE THREAD

**Issue by Athanasius** [inorton/EDMCHits#21]
Hi,  I'm the new maintainer for EDMC itself.  I intend to move releases over to Python 3.7 sometime in the next 1-2 weeks.  As such your users who upgrade EDMC will see your plugin stop working at that point.

I'm first looking at adding some code to the upcoming final Python 2.7-based release of EDMC to detect plugins that don't yet have a `plugin_start3()` method and alert the user.  So your users will start getting that alert when I release (what is planned to be) 3.4.6.0 / 3.46.

If you check [EDMC Available Plugins](https://github.com/EDCD/EDMarketConnector/wiki/Plugins#available-plugins) I can tell you that at least 'Habitable Zone' has already updated, so you could use it as a reference.  Several others have as well, including dual Python 2.7/3.7 support.

**Comment by inorton** [comment]
Hi, I have updated this but forgot to say here! 👍
