### ISSUE TITLE
Unable to activate this plugin?

### ISSUE THREAD

**Issue by badbud65** [inorton/EDMCHits#9]
I've extracted HITS and EDMCOverlay-master into EDMC Plugins directory but I don't get anything when jumping between systems.

They are both shown as enabled Plugins in the settings menu for EDMC.

Server address is: edmc.edhits.space:8080

The game is running on the Primary monitor of a 3 monitor setup and is running in Borderless mode.

What am I doing wrong?

**Comment by inorton** [comment]
Hi Bud,  When HITS is active you should see another process/window called "EDMCOverlay".   Are you trying to run the build from source?  I highly recommend you use the installer.

**Comment by badbud65** [comment]
I followed these instructions, and there is no installation .exe.

> 
> > Installation
> -------------
> 
> Open up EDMC's Settings menu and go to the "Plugins" tab. Click "Open" and
> simply unpack the folders from the "Plugins" folder (in your downloaded zip)
> into this folder.
> 
> After unpacking you will need to "unblock" the EDMCOverlay.exe program, 
> either by running it or using the file properties dialog (note! this is not 
> signed yet).
> 
> Once you have done the above simply restart EDMC and you should see system 
> updates each time you jump.

Also there is no 'EDMCOverlay.exe' file in any of the zip's I downloaded. Nor is this process running.

I have downloaded the following and extracted them all into the EDMC plugins folder

EDMCHits-master
EDMCOverlay-master
Overlay.NET-master

I've downloaded and installed HITS from here: https://github.com/inorton/EDMCHits/releases

**Comment by inorton** [comment]
Hi Bud, those are instructions for EDMCOverlay only, it can be tricky to setup (they are a bit out of date actually) but the good news is the easiest and best supported way is to use the HITS installer (it bundles a build of EDMCOverlay).  You should delete your existing hits or edmcoverlay folders from the plugins directory and run the installer instead.  

Be sure to get the .msi file, not the zip

They are available here: https://github.com/inorton/EDMCHits/releases

0.2.9 is the current version out now.
